### ISSUE TITLE
Multiline strings screw up end of file handling by eating the artificial final return characters instead of terminating their read and attaching their term

### ISSUE THREAD

**Issue by makoConstruct** [makoConstruct/termpose#2]
This is a surprisingly revelatory issue. If there is an art to writing parsers, I did not know it when I began writing this one.

**Comment by makoConstruct** [comment]
Ended up changing every mode to take an isEndOfFile boolean. Should I have used an EOF character? I'm not inclined to forbid certain characters unnecessarily.

**Comment by qpfiffer** [comment]
:package:

**Comment by makoConstruct** [comment]
I mean, what if someone decides they want to use the EOF character in their language constructs? Who am I to tell them they can't have a `\Z` operator?

**Comment by qpfiffer** [comment]
What kind of Machiavellian madman has multiple EOF characters in a single file, especially one supposedly containing a markup language?

**Comment by makoConstruct** [comment]
A free one, quinlan. A free one. */me sheds optimism tears*

**Comment by qpfiffer** [comment]
I believe in you, buddy
