### ISSUE TITLE
Windows newline is \r\n, not \n\r

### ISSUE THREAD

**Issue by felixrabe** [makoConstruct/termpose#7]
I found this in the woodslist spec.

**Comment by felixrabe** [comment]
[This](https://github.com/makoConstruct/termpose/blob/f784aca4e5f8931bd255fcf1047d9813ac7b0b8f/spec.md#syntax-rules)

:newline = "`\n`", "`\r`", or if a `\n` is immediately followed by a `\r`, this pair of characters constitutes only a single :newline "`\n``\r`" (it's a windows compatability thing)

[should be](https://en.wikipedia.org/wiki/Newline#Representation)

:newline = "`\n`", "`\r`", or if a `\r` is immediately followed by a `\n`, this pair of characters constitutes only a single :newline "`\r``\n`" (it's a windows compatability thing)

**Comment by makoConstruct** [comment]
:scream: Wow. I wish I could go back and figure out how the heck my past became convinced that it was the other way around, but I guess we'll never know.
